config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  get "about", to: "pages#about"

  resources :articles

  get "signup", to: "users#new"
  
  resources :users, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
    uniqueness: { case_sensitive: false },  
    length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  
  def current_user
    if session[:user_id] 
      @current_user ||= User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to do that."
      redirect_to login_path
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index] 
  before_action :require_same_user, only: [:edit, :update, :destroy ]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def show
    
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created succesfully."
      redirect_to @article
    else
      render :new
    end
  end

  def edit
  
  end

  def update 
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit 
    end
  end

  def destroy  
    @article.destroy
    redirect_to articles_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end
  
  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin? 
      flash[:alert] = "You can edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show] 


  def index 
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end 
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created succesfully"
      redirect_to @category
    else
      render :new
    end

  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)

  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end

  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can do this"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to articles_path
    end
  end

  def create 
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id 
      flash[:notice] = "Logged in succesfully"
      redirect_to user
    else
      flash.now[:alert] = "Something is wrong with your login details!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out succesfully"
    redirect_to articles_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
 
  def new
    @user = User.new
  end

  def show
    
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    
  end

  def create 
    @user = User.new(user_params)

    if @user.save 
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.username}, you have succesfully signed up!"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @user.update(user_params)
      redirect_to @user
      flash[:notice] = "Updated succesfully"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles succesfully deleted"
    redirect_to articles_path
  end

  private

  def user_params 
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can can edit or delete only your own profile"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

  


end

app/views/articles/_article.html.erb
<div class="container">
      <% @articles.each do |article| %>
        <div class="row justify-content-md-center">
          <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
              <div class="card-header">
                <% if article.user %>
                  by <%= link_to article.user.username, user_path(article.user) %>
                <% end %>
              </div>
              <% if article.categories.any? %>
                  <div class="mt-2"><%= render article.categories %></div>
                <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
                <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
                <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                  <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info"%>
                  <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete,data: { Confirm: "Are you sure?"} %>
                <% end %>
              </div>
              <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago </small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

app/views/articles/_form.html.erb
<div class="container">
  
  <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', obj: @article %>
      <%= form_with model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true do |form| %>
        <div class="form-group row mt-4">
            <%= form.label :title, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
            </div>
        </div>
        <div class="form-group row mt-4">
          <%= form.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= form.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
          <div class="form-group row mt-4">
            <%= form.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= form.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Make your selection (can be empty):"}, { multiple: true, size: 2, class: "form-select shadow rounded"} )%>

        </div>
    </div>
      
        
        <div class="form-group row mt-4 justify-content-center">
          <%= form.submit class: "btn btn-outline-light" %>
        </div> 
      <% end %>
      
    </div>
    <div class="m-3">
    <%= link_to "[ Cancel and return to articles listing page ]", articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
  <h1 class="text-center mt-4">Listing all articles</h1>
  
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  
  <%= render 'article' %>
  
  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
  <h1 class="text-center mt-4">Showing article</h1>
    <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
              <div class="card-header">
                <h5>by <%= @article.user.username %></h5>
                <%= link_to gravatar_for(@article.user, size: 150), user_path(@article.user) %>
              </div>
              <% if @article.categories.any? %>
                  <div class="mt-2"><%= render @article.categories %></div>
                <% end %>
              <div class="card-body">
                <h5 class="card-title text-left text-success"><%=  @article.title %></h5>
                
                <div class="card-text"><%= simple_format(@article.description) %></div>    
                  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>            
                    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info"%>
                    <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete,data: { Confirm: "Are you sure?"} %>
                  <% end %>
                </div>
              <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago </small>
              </div>
            </div>
          </div>
        </div>
    </div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info text-light m-1" %>

app/views/categories/_form.html.erb
<div class="container">
  
  <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', obj: @category %>
      <%= form_with model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true do |form| %>
        <div class="form-group row mt-4">
            <%= form.label :name, "Category name", class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Category name" %>
            </div>
        </div>
        
        <div class="form-group row mt-4 justify-content-center">
          <%= form.submit class: "btn btn-outline-light" %>
        </div> 
      <% end %>
      
    </div>
    <div class="m-3">
    <%= link_to "[ Cancel and return to categories listing page ]", categories_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>


<div class="container">
      <% @categories.each do |category| %>
        <div class="row justify-content-md-center">
          <div class="col-4 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
              <div class="card-body">
                <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
              </div>
               <%= pluralize(category.articles.count, "article") %> 

              <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(category.created_at) %> ago, edited <%= time_ago_in_words(category.updated_at) %> ago </small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
 <h1 class="text-center mt-4"><%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h1>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark">
  <div class="container text-center">
    <span class="text-muted">Copyright Roshan Ali</span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, message|%>
  <% if name == 'notice' %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
    </div>
  <% else %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "AlphaBlog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>
            <%= link_to "All articles", articles_path, class: "dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>
            <%= link_to "All categories", categories_path, class: "dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>
       
        <% if logged_in? %>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
          </ul>
        </li>
          <li class="nav-item">
            <%=  link_to "Log out", logout_path, class: "nav-link", method: :delete %>
          </li>

        <% else %>
           <li class="nav-item">
          <%=  link_to "Log in", login_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%=  link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">  
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <div id="page-content">  
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> About </h1>

  <%= link_to "Articles listing", articles_path %> |
  <%= link_to "Home page", root_path %> |

app/views/pages/home.html.erb
<h1>Welcome to the Homepage</h1>


  
<div id="home-container" class="text-center">
<div class="jumbotron h-100 p-5 text-dark bg-dark jumbotron-image rounded-3">
  <h1 class="display-5 fw-bold">AlphaBlog</h1>
  <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors occured which prevented the <%= obj.class.name.downcase %> from being saved:</h4>
  <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>
      
<% end %>

app/views/users/_form.html.erb
<div class="container">
  
  <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', obj: @user %>
      <%= form_with model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true do |form| %>
        <div class="form-group row mt-4">
            <%= form.label :username, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= form.text_field :username, class: "form-control shadow rounded", placeholder: "Username" %>
            </div>
        </div>
        <div class="form-group row mt-4">
          <%= form.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= form.email_field :email, class: "form-control shadow rounded", placeholder: "Email" %>
          </div>
        </div>
         <div class="form-group row mt-4">
          <%= form.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= form.password_field :password, rows: 10, class: "form-control shadow rounded", placeholder: "Password" %>
          </div>
        </div>
       
        
        <div class="form-group row mt-4 justify-content-center">
          <%= form.submit(@user.new_record? ? "Sign up" : "Update", class: "btn btn-outline-light" )%>
        </div> 
      <% end %>
      
    </div>
    <div class="m-3">
    <%= link_to "[ Cancel and return to articles listing page ]", articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Users</h1>

 <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
 

<div class="container">
      <% @users.each do |user| %>
        <div class="row justify-content-md-center">
          <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
              <div class="card-header">
                 <%= link_to user.username, user %>
              </div>
              <div class="card-body">
                <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user %></h5>
                <p class="card-text"><%= pluralize(user.articles.count, "articles" ) %></p>
                <%= link_to "View profile", user, class: "btn btn-outline-success" %>
                <% if logged_in? %> 
                  <% if user == current_user %>
                  <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info"%>
                  <% end %>
                <% end %>
                <% if logged_in? && current_user.admin? %>
                  <%= link_to 'Delete user', user_path(user), class: "btn btn-outline-danger", method: :delete, 
                  data: { confirm: "Are you sure you want to delete this user?" }%>
                <% end %>
              </div>
              <div class="card-footer text-muted">
              <small>Joined <%= time_ago_in_words(user.created_at) %> ago, edited <%= time_ago_in_words(user.updated_at) %> ago </small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
     <div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
  </div>
 

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>

 <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">User's Articles</h1>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>